/*
<< 변수 >> 치환 필요

<< ECR URI >>      => ex) 123456789012.dkr.ecr.us-east-1.amazonaws.com
ex) 123456789012.dkr.ecr.us-east-1.amazonaws.com/eshop-backend:latest
*/
pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: gradle
spec:
  containers:
  - name: gradle
    image: gradle:6.3.0-jdk11
    command:
    - cat
    tty: true
    env:
      # Define the environment variable
      - name: CRED
        valueFrom:
          configMapKeyRef:
            name: jenkinscred
            key: ECR_CREDENTIAL_JSON
  restartPolicy: Never
"""      
    }
  }
  environment {
    IMAGE_REGISTRY = "<< ECR URI >>"
  }
  stages {
    stage('build and push docker image') {
                  
      steps {
        container('gradle') {
          dir('eshop-cartservice') {
            sh 'gradle jib --no-daemon --image ${IMAGE_REGISTRY}/eshop-cartservice:latest -Djib.to.auth.username=AWS -Djib.to.auth.password=$CRED'
          }
        }
      }
    }
  }
}